package commands

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	helperfuncs "github.com/iartmediums/mk-cli/internal/helper_funcs"
)

const (
	firstRunNoticeName = ".first_run_notice_shown"
	templateExt        = ".mktmpl"
)

const defaultGoTemplate = `# dir
cmd
cmd/{{PN}}
internal
internal/app

# content .gitignore
bin/
dist/
coverage.out

# content .editorconfig
root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
indent_style = tab
indent_size = 4
trim_trailing_whitespace = true

[*.md]
indent_style = space
indent_size = 2
trim_trailing_whitespace = false

# content README.md
# {{PN}}

Small Go service scaffold generated by ` + "`mk`" + `.

## Development

` + "```bash" + `
go test ./...
go run ./cmd/{{PN}}
` + "```" + `

## Layout

- ` + "`cmd/{{PN}}`" + `: application entrypoint
- ` + "`internal/app`" + `: app wiring and core behavior

# content Makefile
APP={{PN}}

.PHONY: run test fmt

run:
	go run ./cmd/$(APP)

test:
	go test ./...

fmt:
	go fmt ./...

# content cmd/{{PN}}/main.go
package main

import (
	"log"

	"{{MODULE}}/internal/app"
)

func main() {
	application := app.New()
	if err := application.Run(); err != nil {
		log.Fatal(err)
	}
}

# content internal/app/app.go
package app

import "fmt"

type App struct {
	name string
}

func New() *App {
	return &App{name: "{{PN}}"}
}

func (a *App) Run() error {
	fmt.Printf("%s is running\n", a.name)
	return nil
}

# content internal/app/app_test.go
package app

import "testing"

func TestNew(t *testing.T) {
	app := New()

	if app == nil {
		t.Fatal("expected app instance, got nil")
	}

	if app.name != "{{PN}}" {
		t.Fatalf("expected app name %q, got %q", "{{PN}}", app.name)
	}
}

# cmd
go mod init {{MODULE}}
go fmt ./...
go test ./...
git init
`

type mkConfig struct {
	Editor             string `json:"editor"`
	Module             string `json:"module"`
	DisableGoDefault   bool   `json:"disableGoDefaultTemp"`
	EditOnTmplCreation bool   `json:"editOnTmplCreation"`
}

type bootstrapResult struct {
	Config       mkConfig
	ConfigDir    string
	TemplatesDir string
	ConfigPath   string
	Created      []string
}

func ensureSetup(printNotice bool) (*bootstrapResult, error) {
	configDir, err := getConfigDir()
	if err != nil {
		return nil, err
	}

	templatesDir := filepath.Join(configDir, "templates")
	configPath := filepath.Join(configDir, "config.json")
	noticePath := filepath.Join(configDir, firstRunNoticeName)
	goTemplatePath := filepath.Join(templatesDir, "go"+templateExt)

	result := &bootstrapResult{
		ConfigDir:    configDir,
		TemplatesDir: templatesDir,
		ConfigPath:   configPath,
	}

	if err := helperfuncs.CreateDir(templatesDir); err != nil {
		return nil, fmt.Errorf("error while creating mk config directories: %w", err)
	}

	cfg, createdConfig, err := ensureConfigFile(configPath)
	if err != nil {
		return nil, err
	}
	result.Config = cfg
	if createdConfig {
		result.Created = append(result.Created, configPath)
	}

	if !cfg.DisableGoDefault {
		createdTemplate, err := ensureDefaultTemplate(goTemplatePath)
		if err != nil {
			return nil, err
		}
		if createdTemplate {
			result.Created = append(result.Created, goTemplatePath)
		}
	}

	if printNotice {
		if _, err := os.Stat(noticePath); os.IsNotExist(err) {
			printFirstRunNotice(result)
			if writeErr := os.WriteFile(noticePath, []byte("shown\n"), 0o644); writeErr != nil {
				return nil, fmt.Errorf("error while storing first-run notice state: %w", writeErr)
			}
		} else if err != nil {
			return nil, fmt.Errorf("error while checking first-run notice state: %w", err)
		}
	}

	return result, nil
}

func getConfigDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("error while getting user home directory: %w", err)
	}
	return filepath.Join(home, ".config", "mk"), nil
}

func getConfigPath() (string, error) {
	configDir, err := getConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "config.json"), nil
}

func getTemplatesDir() (string, error) {
	configDir, err := getConfigDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(configDir, "templates"), nil
}

func defaultConfig() mkConfig {
	return mkConfig{
		Editor:             "",
		Module:             "",
		DisableGoDefault:   false,
		EditOnTmplCreation: true,
	}
}

func ensureConfigFile(path string) (mkConfig, bool, error) {
	if data, err := os.ReadFile(path); err == nil {
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(data, &raw); err != nil {
			return mkConfig{}, false, fmt.Errorf("error while parsing %s: %w", path, err)
		}

		var cfg mkConfig
		if err := json.Unmarshal(data, &cfg); err != nil {
			return mkConfig{}, false, fmt.Errorf("error while parsing %s: %w", path, err)
		}

		updated := false
		defaults := defaultConfig()
		if _, ok := raw["editor"]; !ok {
			cfg.Editor = defaults.Editor
			updated = true
		}
		if _, ok := raw["module"]; !ok {
			cfg.Module = defaults.Module
			updated = true
		}
		if _, ok := raw["disableGoDefaultTemp"]; !ok {
			cfg.DisableGoDefault = defaults.DisableGoDefault
			updated = true
		}
		if _, ok := raw["editOnTmplCreation"]; !ok {
			cfg.EditOnTmplCreation = defaults.EditOnTmplCreation
			updated = true
		}
		if updated {
			if err := writeConfigFile(path, cfg); err != nil {
				return mkConfig{}, false, err
			}
		}
		return cfg, updated, nil
	} else if !os.IsNotExist(err) {
		return mkConfig{}, false, fmt.Errorf("error while reading %s: %w", path, err)
	}

	cfg := defaultConfig()
	if err := writeConfigFile(path, cfg); err != nil {
		return mkConfig{}, false, err
	}
	return cfg, true, nil
}

func writeConfigFile(path string, cfg mkConfig) error {
	data, err := json.MarshalIndent(cfg, "", "  ")
	if err != nil {
		return fmt.Errorf("error while preparing config: %w", err)
	}
	data = append(data, '\n')
	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("error while writing %s: %w", path, err)
	}
	return nil
}

func ensureDefaultTemplate(path string) (bool, error) {
	if _, err := os.Stat(path); err == nil {
		return false, nil
	} else if !os.IsNotExist(err) {
		return false, fmt.Errorf("error while checking %s: %w", path, err)
	}

	if err := helperfuncs.WriteFile(path, defaultGoTemplate); err != nil {
		return false, fmt.Errorf("error while writing %s: %w", path, err)
	}
	return true, nil
}

func printFirstRunNotice(result *bootstrapResult) {
	fmt.Fprintln(os.Stderr, "mk first-run setup")
	fmt.Fprintln(os.Stderr)
	fmt.Fprintf(os.Stderr, "Created defaults under %s.\n", result.ConfigDir)
	fmt.Fprintln(os.Stderr, "Manual steps for full capability:")
	fmt.Fprintf(os.Stderr, "  - Set `editor` in %s or export $VISUAL / $EDITOR.\n", result.ConfigPath)
	fmt.Fprintf(os.Stderr, "  - Set `module` in %s if you want Go templates to use a custom default module path.\n", result.ConfigPath)
	fmt.Fprintf(os.Stderr, "  - Review %s if you want a different default Go scaffold.\n", filepath.Join(result.TemplatesDir, "go"+templateExt))
	fmt.Fprintln(os.Stderr, "Run `mk help` to see available commands.")
}

func configSetupHandler(cfg *cmdConfig) error {
	result, err := ensureSetup(false)
	if err != nil {
		return err
	}

	if len(result.Created) == 0 {
		fmt.Printf("mk config setup: all default files already exist in %s\n", result.ConfigDir)
	} else {
		fmt.Printf("mk config setup: created %d file(s)\n", len(result.Created))
		for _, path := range result.Created {
			fmt.Printf("  %s\n", path)
		}
	}

	printFirstRunNotice(result)
	noticePath := filepath.Join(result.ConfigDir, firstRunNoticeName)
	if err := os.WriteFile(noticePath, []byte("shown\n"), 0o644); err != nil {
		return fmt.Errorf("error while storing first-run notice state: %w", err)
	}
	return nil
}

func buildDefaultModulePath(cfg mkConfig, projectName string) string {
	module := strings.TrimSpace(cfg.Module)
	if module == "" {
		return projectName
	}

	replaced := strings.ReplaceAll(module, "{{.PN}}", projectName)
	replaced = strings.ReplaceAll(replaced, "{{PN}}", projectName)
	if strings.TrimSpace(replaced) == "" {
		return projectName
	}
	return replaced
}
